name: EEG-Diffusion
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10.8
  - pip
  - pip:
    - -i https://mirrors.aliyun.com/pypi/simple/
    - torch==2.3.0
    - torchvision==0.18.0
    - torchaudio==2.3.0
    - numpy==1.26.4
    - matplotlib==3.9.2
    - tqdm==4.66.5
    - scikit-image==0.24.0
    - jupyterlab==4.4.5
    - pandas==2.2.0
    - transformers==4.38.2
    - diffusers==0.24.0
    - braindecode==0.8.1
    - open_clip_torch==2.23.0
    - clip-retrieval==2.44.0
    - clip==0.2.0
    - kornia==0.7.2
    - umap-learn==0.5.5
    - dalle2-pytorch==1.15.6
    - info-nce-pytorch==0.1.4
    - pytorch-msssim==1.0.0
    - reformer_pytorch==1.4.4
    - mne==1.5.1
    - wandb==0.16.3
    - einops==0.7.0
    - ftfy==6.1.3
    - regex==2023.10.3
    - accelerate==0.25.0
    - huggingface_hub==0.19.4